version: '2'

services:
  opensource-contribution-leaderboard:
    image: rohanlekhwani/opensource-contribution-leaderboard:latest
    volumes:
      - ./server/config.json:/dist/server/config.json
      - ./assets/data:/data
    ports:
      - "8080:8080"